@TodoApp.Api_HostAddress = http://localhost:5000

### Health
GET {{TodoApp.Api_HostAddress}}/api/health
Accept: application/json

### Sign up
POST {{TodoApp.Api_HostAddress}}/api/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### Sign in
POST {{TodoApp.Api_HostAddress}}/api/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### List todos
GET {{TodoApp.Api_HostAddress}}/api/todos
Accept: application/json

### Create todo
POST {{TodoApp.Api_HostAddress}}/api/todos
Content-Type: application/json

{
  "title": "Test todo"
}
